[package]
name = "website"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5.17"
tokio = { version = "1.21.2", features = [ "full" ] }
tower-http = { version =  "0.3.4", features = [ "fs" ] }
tower = "0.4.13"
rust-embed = "6.4.2"
mime_guess = "2.0.4"
http = "0.2.8"
